# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password: root

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MTc1ZTQwYWU0MjYxNTI1NTgzMjFiYWYwNmFkM2I0OWU3ZTg1MGM2ZDdhOTQ4ZDBiMjdkZTdhOWNhMGE2NmJiNTE3MWFiNGI0MGM2NWJkNmU1Mzk5NzI3MzM4ZGIzMGMyNmExYWRmNmY5ZGU1YjhlMzhiMmE3MDUyYTBjN2M2Njk=
