package com.mokeal.mokeal.domain;

import static com.mokeal.mokeal.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ServicioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioAllPropertiesEquals(Servicio expected, Servicio actual) {
        assertServicioAutoGeneratedPropertiesEquals(expected, actual);
        assertServicioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioAllUpdatablePropertiesEquals(Servicio expected, Servicio actual) {
        assertServicioUpdatableFieldsEquals(expected, actual);
        assertServicioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioAutoGeneratedPropertiesEquals(Servicio expected, Servicio actual) {
        assertThat(actual)
            .as("Verify Servicio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioUpdatableFieldsEquals(Servicio expected, Servicio actual) {
        assertThat(actual)
            .as("Verify Servicio relevant properties")
            .satisfies(a -> assertThat(a.getTipoServicio()).as("check tipoServicio").isEqualTo(expected.getTipoServicio()))
            .satisfies(a -> assertThat(a.getZona()).as("check zona").isEqualTo(expected.getZona()))
            .satisfies(a -> assertThat(a.getFrecuencia()).as("check frecuencia").isEqualTo(expected.getFrecuencia()))
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
            .satisfies(a -> assertThat(a.getHoraInicio()).as("check horaInicio").isEqualTo(expected.getHoraInicio()))
            .satisfies(a ->
                assertThat(a.getDuracionHoras())
                    .as("check duracionHoras")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDuracionHoras())
            )
            .satisfies(a -> assertThat(a.getNumTrabajadores()).as("check numTrabajadores").isEqualTo(expected.getNumTrabajadores()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getDireccion()).as("check direccion").isEqualTo(expected.getDireccion()))
            .satisfies(a -> assertThat(a.getMunicipio()).as("check municipio").isEqualTo(expected.getMunicipio()))
            .satisfies(a -> assertThat(a.getNotas()).as("check notas").isEqualTo(expected.getNotas()))
            .satisfies(a ->
                assertThat(a.getPrecioTotal())
                    .as("check precioTotal")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioTotal())
            )
            .satisfies(a ->
                assertThat(a.getDescuento()).as("check descuento").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getDescuento())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioUpdatableRelationshipsEquals(Servicio expected, Servicio actual) {
        assertThat(actual)
            .as("Verify Servicio relationships")
            .satisfies(a -> assertThat(a.getCliente()).as("check cliente").isEqualTo(expected.getCliente()))
            .satisfies(a -> assertThat(a.getTarifa()).as("check tarifa").isEqualTo(expected.getTarifa()))
            .satisfies(a -> assertThat(a.getTrabajadoreses()).as("check trabajadoreses").isEqualTo(expected.getTrabajadoreses()));
    }
}
