package com.mokeal.mokeal.domain;

import static com.mokeal.mokeal.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TarifaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarifaAllPropertiesEquals(Tarifa expected, Tarifa actual) {
        assertTarifaAutoGeneratedPropertiesEquals(expected, actual);
        assertTarifaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarifaAllUpdatablePropertiesEquals(Tarifa expected, Tarifa actual) {
        assertTarifaUpdatableFieldsEquals(expected, actual);
        assertTarifaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarifaAutoGeneratedPropertiesEquals(Tarifa expected, Tarifa actual) {
        assertThat(actual)
            .as("Verify Tarifa auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarifaUpdatableFieldsEquals(Tarifa expected, Tarifa actual) {
        assertThat(actual)
            .as("Verify Tarifa relevant properties")
            .satisfies(a -> assertThat(a.getZona()).as("check zona").isEqualTo(expected.getZona()))
            .satisfies(a -> assertThat(a.getTipoServicio()).as("check tipoServicio").isEqualTo(expected.getTipoServicio()))
            .satisfies(a ->
                assertThat(a.getPrecioFirstHora())
                    .as("check precioFirstHora")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioFirstHora())
            )
            .satisfies(a ->
                assertThat(a.getPrecioHoraAdicional())
                    .as("check precioHoraAdicional")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioHoraAdicional())
            )
            .satisfies(a -> assertThat(a.getMinimoHoras()).as("check minimoHoras").isEqualTo(expected.getMinimoHoras()))
            .satisfies(a ->
                assertThat(a.getPrecioPorKm())
                    .as("check precioPorKm")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioPorKm())
            )
            .satisfies(a -> assertThat(a.getActiva()).as("check activa").isEqualTo(expected.getActiva()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarifaUpdatableRelationshipsEquals(Tarifa expected, Tarifa actual) {
        // empty method
    }
}
