package com.mokeal.mokeal.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TrabajadorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrabajadorAllPropertiesEquals(Trabajador expected, Trabajador actual) {
        assertTrabajadorAutoGeneratedPropertiesEquals(expected, actual);
        assertTrabajadorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrabajadorAllUpdatablePropertiesEquals(Trabajador expected, Trabajador actual) {
        assertTrabajadorUpdatableFieldsEquals(expected, actual);
        assertTrabajadorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrabajadorAutoGeneratedPropertiesEquals(Trabajador expected, Trabajador actual) {
        assertThat(actual)
            .as("Verify Trabajador auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrabajadorUpdatableFieldsEquals(Trabajador expected, Trabajador actual) {
        assertThat(actual)
            .as("Verify Trabajador relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getNotas()).as("check notas").isEqualTo(expected.getNotas()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrabajadorUpdatableRelationshipsEquals(Trabajador expected, Trabajador actual) {
        assertThat(actual)
            .as("Verify Trabajador relationships")
            .satisfies(a -> assertThat(a.getServicioses()).as("check servicioses").isEqualTo(expected.getServicioses()));
    }
}
